all: Pair.class Graph.class EdgeDataGraph.class KevinBacon.class 

Pair.class: Pair.java
	javac Pair.java

Graph.class: Graph.java
	javac Graph.java

KevinBacon.class:KevinBacon.java
	javac KevinBacon.java

EdgeDataGraph.class:EdgeDataGraph.java
	javac EdgeDataGraph.java

clean:
	rm *.class
