all: Anagrams.class Sierpinski.class Palindrome.class Fibonaccik.class

Anagrams.class: Anagrams.java
	javac Anagrams.java

Sierpinski.class:  Sierpinski.java
	javac Sierpinski.java

Palindrome.class: Palindrome.java
	javac Palindrome.java

Fibonaccik.class:Fibonaccik.java
	javac Fibonaccik.java

clean:
	rm *.class
	rm *.java~
